import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const apercu = localFont({
  src: [
    {
      path: "../../public/fonts/ApercuPro-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/ApercuPro-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/ApercuPro-Light.woff2",
      weight: "200",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${apercu.className}`}>{children}</body>
    </html>
  );
}
